# retrieval settings

datasets:
  batch_size: 16

  collate_fn:
    name: "CollateFn"

  folder:
    name: "Folder"

  transformers:
    names: ["PadResize", "ToTensor", "Normalize"]
    PadResize:
      size: 224
    Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

model:
  name: "resnet50"
  resnet50:
    load_checkpoint: "torchvision://resnet50"

extract:
  assemble: 0

  extractor:
    name: "ResSeries"
    ResSeries:
      extract_features: ["pool5"]

  splitter:
    name: "Identity"

  aggregators:
    names: ["GeM"]

index:
  query_fea_dir: "/data/features/best_features/caltech/query"
  gallery_fea_dir: "/data/features/best_features/caltech/gallery"

  feature_names: ["pool5_GeM"]

  dim_processors:
    names: ["L2Normalize", "PCA", "L2Normalize"]
    PCA:
      proj_dim: 512
      whiten: False
      train_fea_dir: "/data/features/best_features/caltech/gallery"
      l2: True

  feature_enhancer:
    name: "DBA"
    DBA:
      enhance_k: 10  # number of the nearest points to be calculated.

  metric:
    name: "KNN"

  re_ranker:
    name: "QEKR"
    QEKR:
      qe_times: 1  # number of query expansion times.
      qe_k: 10  # number of the neighbors to be combined.
      k1: 20  # hyper-parameter for calculating jaccard distance.
      k2: 6  # hyper-parameter for calculating local query expansion.
      lambda_value: 0.3  # hyper-parameter for calculating the final distance.

evaluate:
  evaluator:
    name: "OverAll"
