# retrieval settings

datasets:
  batch_size: 16

  collate_fn:
    name: "CollateFn"

  folder:
    name: "Folder"

  transformers:
    names: ["ShorterResize", "CenterCrop", "ToTensor", "Normalize"]
    ShorterResize:
      size: 256
    CenterCrop:
      size: 224
    Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

model:
  name: "resnet50"
  resnet50:
    load_checkpoint: "torchvision://resnet50"

extract:
  assemble: 0

  extractor:
    name: "ResSeries"
    ResSeries:
      extract_features: ["pool5"]

  splitter:
    name: "Identity"

  aggregators:
    names: ["SCDA"]

index:
  query_fea_dir: "/data/features/best_features/cub/query"
  gallery_fea_dir: "/data/features/best_features/cub/gallery"

  feature_names: ["pool5_SCDA"]

  dim_processors:
    names: ["L2Normalize", "PCA", "L2Normalize"]
    PCA:
      proj_dim: 512
      whiten: False
      train_fea_dir: "/data/features/best_features/cub/gallery"
      l2: True

  feature_enhancer:
    name: "Identity"

  metric:
    name: "KNN"

  re_ranker:
    name: "KReciprocal"
    KReciprocal:
      k1: 20  # hyper-parameter for calculating jaccard distance.
      k2: 6  # hyper-parameter for calculating local query expansion.
      lambda_value: 0.3  # hyper-parameter for calculating the final distance.

evaluate:
  evaluator:
    name: "OverAll"

