datasets:
  batch_size: 16

  collate_fn:
    name: "CollateFn"

  folder:
    name: "Folder"

  transformers:
    names: ["DirectResize", "ToTensor", "Normalize"]
    DirectResize:
      size: (224, 224) #(448, 448) #(224, 224)
    Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

model:
  name: "resnet50"
  resnet50:
    load_checkpoint: "/data/places365_model/res50_places365.pt"

extract:
  assemble: 0

  extractor:
    name: "ResSeries"
    ResSeries:
      extract_features: ["pool5"]

  splitter:
    name: "Identity"

  aggregators:
    names: ["Crow"]

index:
  query_fea_dir: "/data/features/best_features/indoor/query"
  gallery_fea_dir: "/data/features/best_features/indoor/gallery"

  feature_names: ["pool5_Crow"]

  dim_processors:
    names: ["L2Normalize", "PCA", "L2Normalize"]
    PCA:
      proj_dim: 512
      whiten: False
      train_fea_dir: "/data/features/best_features/indoor/gallery"
      l2: True

  feature_enhancer:
    name: "DBA"
    DBA:
      enhance_k: 10  # number of the nearest points to be calculated.

  metric:
    name: "KNN"

  re_ranker:
    name: "QE"
    QE:
      qe_times: 1  # number of query expansion times.
      qe_k: 10  # number of the neighbors to be combined.

evaluate:
  evaluator:
    name: "OverAll"

