model: beit_large_patch16_512.in22k_ft_in22k_in1k
pretrained: True

data_dir: /home/data1/changhao/iBioHash/Datasets
train_split: imagenet_iBioHash_Train

val_split: iBioHash_Sampled40_10/validation

num_classes: 1000
img_size: 512
batch_size: 4
freeze_layer: 12
checkpoint_hist: 30

aa: rand-m9-mstd0.5


sync_bn: True

epochs: 30
lr: 0.001

eval_metric: loss
sched: multistep
warmup_epochs: 10
decay_milestones: [5,20,25]

