model: eva_large_patch14_336.in22k_ft_in22k_in1k
pretrained: True

data_dir: /home/data1/changhao/iBioHash/Datasets
#train
train_split: imagenet_iBioHash_Train
#val
val_split: iBioHash_Sampled40_10/validation

num_class: 1000
img_size: 336
batch_size: 8
freeze_layer: 6
checkpoint_hist: 30

aa: rand-m9-mstd0.5

sync_bn: True
epochs: 30
eval_metric: loss
lr: 0.001
sched: multistep
warmup_epochs: 3
decay_milestones: [10,20,25]

iBioHash_image_fitter_query_gallery